name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: Find and Link Artifact
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          rally-api-key: ${{ secrets.RALLYKEY }}
          rally-story-prefix: 'S'
          rally-defect-prefix: 'DE'

      - name: Leave a found comment
        if:
          ${{ !failure() &&  steps.test-action.outputs.rally-artifact-url != ''
          }}
        uses: mshick/add-pr-comment@v2
        with:
          message:
            '<h3>📖 <a href="${{ steps.test-action.outputs.rally-artifact-url
            }}">${{ steps.test-action.outputs.rally-artifact-formatted-id }}</a>
            </h3> <details><summary><h3>${{
            steps.test-action.outputs.rally-artifact-name }}</h3></summary>
            <hr/> <p>${{ steps.test-action.outputs.rally-artifact-description
            }}</p></details>'

      - name: Leave a not found comment
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v2
        with:
          message:
            '❌ Could not find a Rally artifact to link to this PR. \nPlease
            ensure that the PR title, description, or a commit message contains
            a Rally story or defect formatted id (e.g. `S123` or `DE123`).'
