name: Find Rally Artifact

on:
  pull_request:

jobs:
  lint:
    name: Find Rally Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Find Rally Artifact
        id: find
        uses: wbeard/action-find-rally-artifact@v1.4
        with:
          rally-api-key: ${{ secrets.RALLYKEY }}
          rally-story-prefix: 'S'
          rally-defect-prefix: 'DE'

      - name: Leave a comment
        id: comment
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message:
            'Found Rally Artifact: ${{ steps.find.outputs.rally-artifact-url }}'
          reactions: '+1'
